name: emajava_docker
services: 
    provider:
        image: developers/provider
        build: 
            context: ./IProvider
            dockerfile: Dockerfile
    consumer:
        image: developers/consumer
        build: 
            context: ./Consumer
            dockerfile: Dockerfile
        depends_on: 
            provider:
                condition: service_started
        volumes: 
            - ./Consumer/logs:/logs
