# Maven 
FROM maven:3.8.1-openjdk-11-slim AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn -e -B dependency:resolve
COPY src ./src
RUN mvn -e -B package

# RTSDK Java
FROM openjdk:11-jre-slim
COPY --from=builder /app/target/Consumer-1.0-jar-with-dependencies.jar /
COPY EmaConfig.xml .
COPY etc ./etc
COPY resources ./resources
# run Consumer-1.0-jar-with-dependencies.jar with CMD
CMD ["java", "-jar","-Dlog4j.configurationFile=/resources/log4j2.xml", "/Consumer-1.0-jar-with-dependencies.jar"]